web/config/routes.rb
Rails.application.routes.draw do

  get '/feriadesoftware' => redirect('http://feriadesoftware.cl')
  get '/informatica' => redirect('http://inf.utfsm.cl')
  get '/facebook' => redirect('https://www.facebook.com/Carryvent')
  get '/usm' => redirect('http://www.usm.cl')
  ActiveAdmin.routes(self)
  resources :rankings
  resources :comments, :only =>[:create, :destroy]

  resources :notifications
  get '/checkNewNotification' => "notifications#checking_new" , as: :checking_new

  get '/eventos' => 'evento#eventos', as: :lista_eventos_user
  get '/evento/:id' => 'evento#show', as: :mostrar_evento
  get '/operario/list_eventos' => "evento#list_eventos", as: :list_eventos
  get '/operario/ruta_evento/:id' => "evento#ruta_evento", as: :ruta_evento

  get '/evento/:id/reserva' => "pasajes#reserva", as: :reserva_pasaje
  post '/evento/:id/reserva' => "pasajes#reserva_send", as: :crear_reserva
  get '/evento/:id/reservado' => "pasajes#reservado", as: :pasaje_reservado
  post '/reserva/concretar/:id' => "pasajes#aceptar_reserva", as: :concretar_reserva
  get '/operario/list_pasajes/:id' => "pasajes#list_pasajes", as: :list_pasajes

  get '/user/:id' => 'user#perfil', as: :perfil_user
  get '/user/:id/editar' => 'user#editar', as: :editar_user

  get 'evento/:evento_id/carpool/publicar' => 'carpool#publicar', as: :publicar_carpool
  post 'evento/:evento_id/carpool/publicar' =>  'carpool#new', as: :new_publicar_carpool
  get 'evento/:evento_id/carpool/:id' => 'carpool#show', as: :mostrar_carpool
 
  post 'evento/:evento_id/carpool/:id' => 'carpool#new_transaction', as: :crear_transaccion_carpool
  get 'evento/carpool/:evento_id/:id/:transaction_id/accept' => 'carpool#aceptar_transaction', as: :aceptar_transaccion
  get 'evento/carpool/:evento_id/:id/:transaction_id/reject' => 'carpool#rechazar_transaction', as: :rechazar_transaccion
  get 'evento/carpool/:evento_id/:id/:transaction_id/delete' => 'carpool#delete_transaction' , as: :borrar_transaccion

  devise_for :users,  :controllers => { :omniauth_callbacks => 'omniauth_callbacks', :registrations => "registrations"  }, :skip => [:sessions, :passwords, :confirmations, :registrations]
  as :user do
    get   '/registrarse' => 'registrations#new',    :as => :new_user_registration
    post  '/registrarse' => 'registrations#create', :as => :user_registration

    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    match 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session,
      :via => Devise.mappings[:user].sign_out_via

    scope '/account' do
      get   '/resetpassword'        => 'devise/passwords#new',    :as => :new_user_password
      put   '/resetpassword'        => 'devise/passwords#update', :as => :user_password
      post  '/resetpassword'        => 'devise/passwords#create'
      get   '/resetpassword/change' => 'devise/passwords#edit',   :as => :edit_user_password

      get   '/confirm'        => 'devise/confirmations#show',   :as => :user_confirmation
      post  '/confirm'        => 'devise/confirmations#create'
      get   '/confirm/resend' => 'devise/confirmations#new',    :as => :new_usern_confirmation

      get '/cancel'   => 'registrations#cancel', :as => :cancel_user_registration
      get '/settings' => 'registrations#edit',   :as => :edit_user_registration
      post '/settings' => 'registrations#update', :as => :update_user_registration

      delete '' => 'devise/registrations#destroy'
    end
  end

  devise_for :publicadors, :skip => [:sessions, :passwords, :confirmations, :registrations]
  as :publicador do
    get 'cv-login' => 'devise/sessions#new', :as => :new_publicador_session
    post 'cv-login' => 'devise/sessions#create', :as => :publicador_session
    match 'cv-logout' => 'devise/sessions#destroy', :as => :destroy_publicador_session,
      :via => Devise.mappings[:publicador].sign_out_via
  end

  authenticated :user do
    root :to => "evento#eventos", as: "authenticated_root"
  end

  authenticated :publicador do
    root :to => "admin/dashboard#index", as: "authenticated_publicador_root"
  end

  root :to => 'index#index'

end

web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <%= favicon_link_tag 'favicon.ico' %>
    <title> Carryvent - <%= yield(:title).empty? ? "¡Viaja con nosotros!" : yield(:title) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry&amp; hl=cl" type="text/javascript"></script>
    <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
    
    <script src='//google-maps-utility-library-v3.googlecode.com/svn/trunk/richmarker/src/richmarker-compiled.js' type='text/javascript'></script>

    <% if content_for?(:head) %>
      <%= yield(:head) %>
    <% end %>

   

</head>

<body>
   <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<%=root_path %>">
                    <%=image_tag "minilogo.png" %><b> Carryvent</b>
                </a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                   <li class="<%=((params[:action] == 'index') and (params[:controller]!= "notifications")) ? 'active' : '' %>">
                    <%= link_to "Inicio", root_path%>
                   </li> 

                  <% if user_signed_in? %>

                    <li class="<%=params[:action] == 'eventos' ? 'active' : '' %>">
                        <%= link_to "Eventos", lista_eventos_user_path %>
                    </li>
                  <% elsif publicador_signed_in? %>

                   'active' if params[:controller] == 'index' and params[:action] == 'index'
                    <li> <%= link_to "Publicar Evento", publicar_evento_path %></li>
                    <li> <%= link_to "Agregar Organizacion", publicar_organization_path %></li>
                    <li><%= link_to "Administrar Eventos", lista_eventos_publicador_path %></li></li>
                    <li><%= link_to notifications_path do%>

                            <span class="badge" id="cantidadNotifications"><%=activitiesCount%></span>Notificaciones

                        <% end %>
                    </li>

                    <li><%= link_to "Logout", destroy_publicador_session_path, :method => :delete %></li>
                  <% end %>
                </ul>

                <% if user_signed_in? %>
                 <ul class="nav navbar-nav navbar-right">
                    <li class="<%=((params[:action] == 'index') and (params[:controller]== "notifications")) ? 'active' : '' %>">
                        <%= link_to notifications_path do%>
                            <span class="bottom" title="Notificaciones" data-original-title="Tooltip on right">
                                <span class="badge <%= @activitiesCount > 0 ? 'alert-warning': ''%>" id="cantidadNotifications" ><%=@activitiesCount%></span>
                                <i class="fa fa-inbox fa-lg"></i><span class="visible-xs">Notificaciones</span> 
                            </span>
                        <% end %>
                    </li>
                    
                    <li class="dropdown">
                        <a id="nombreUsuario" href="#" data-toggle="dropdown" class="dropdown-toggle"> 
                        <% if current_user.foto.present? %>
                        <img src="<%=current_user.foto.thumb.url %>", class ="img-circle">
                        <% else %>
                        <img src="/assets/place_user.png", class="img-circle", style="width:30px;heigh:30px">
                        <% end %>

                        <%=current_user.nombre%><b class="caret"></b></a>

                        <ul class="dropdown-menu">
                            <li><%= link_to  "Perfil", perfil_user_path(current_user)%></li>
                            <li class="divider"></li>
                            <li> <%= link_to "Salir", destroy_user_session_path, :method => :delete %></li>
                        </ul>
                    </li>
                </ul>
                <% end %>

            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>


<div id="wrap">
  <div id="main">
    <%= yield %>
  </div>
</div>
<footer class="footer"></footer>


<!-- Footer -->
<footer class="navbar navbar-default navbar-fixed-bottom hidden-xs">
    <div class="container">
        <div class="text-center">
            <p>Copyright &copy; Carryvent 2014</p>
        </div>
    </div>
</footer>

 <script type="text/javascript">
    $(".bottom").tooltip({
        placement: "bottom"
    });
    </script>

</body>
</html>

web/app/views/layouts/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <%= favicon_link_tag 'favicon.ico' %>
    <title> Carryvent - <%= yield(:title).empty? ? "¡Viaja Seguro!" : yield(:title) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag :defaults, 'efecto_grayscale' %>
    <%= csrf_meta_tags %>


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
    <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
    
    <script src='//google-maps-utility-library-v3.googlecode.com/svn/trunk/richmarker/src/richmarker-compiled.js' type='text/javascript'></script>



</head>

<body style="padding-top: 0px;">
<div id="wrap">
  <div id="main">
    <%= yield %>
  </div>
</div>
<footer class="footer"></footer>


<!-- Footer -->
<footer class="navbar navbar-default navbar-fixed-bottom">
    <div class="container">
        <div class="text-center">
            <p>Copyright &copy; Carryvent 2014</p>
        </div>
    </div>
</footer>

</body>
</html>