web/config/routes.rb
Rails.application.routes.draw do

  get '/feriadesoftware' => redirect('http://feriadesoftware.cl')
  get '/informatica' => redirect('http://inf.utfsm.cl')
  get '/facebook' => redirect('https://www.facebook.com/Carryvent')
  get '/usm' => redirect('http://www.usm.cl')
  ActiveAdmin.routes(self)
  resources :rankings
  resources :comments, :only =>[:create, :destroy]

  resources :notifications
  get '/checkNewNotification' => "notifications#checking_new" , as: :checking_new

  get '/eventos' => 'evento#eventos', as: :lista_eventos_user
  get '/evento/:id' => 'evento#show', as: :mostrar_evento
  get '/operario/list_eventos' => "evento#list_eventos", as: :list_eventos
  get '/operario/ruta_evento/:id' => "evento#ruta_evento", as: :ruta_evento

  get '/evento/:id/reserva' => "pasajes#reserva", as: :reserva_pasaje
  post '/evento/:id/reserva' => "pasajes#reserva_send", as: :crear_reserva
  get '/evento/:id/reservado' => "pasajes#reservado", as: :pasaje_reservado
  post '/reserva/concretar/:id' => "pasajes#aceptar_reserva", as: :concretar_reserva
  get '/operario/list_pasajes/:id' => "pasajes#list_pasajes", as: :list_pasajes

  get '/user/:id' => 'user#perfil', as: :perfil_user
  get '/user/:id/editar' => 'user#editar', as: :editar_user

  get 'evento/:evento_id/carpool/publicar' => 'carpool#publicar', as: :publicar_carpool
  post 'evento/:evento_id/carpool/publicar' =>  'carpool#new', as: :new_publicar_carpool
  get 'evento/:evento_id/carpool/:id' => 'carpool#show', as: :mostrar_carpool
 
  post 'evento/:evento_id/carpool/:id' => 'carpool#new_transaction', as: :crear_transaccion_carpool
  get 'evento/carpool/:evento_id/:id/:transaction_id/accept' => 'carpool#aceptar_transaction', as: :aceptar_transaccion
  get 'evento/carpool/:evento_id/:id/:transaction_id/reject' => 'carpool#rechazar_transaction', as: :rechazar_transaccion
  get 'evento/carpool/:evento_id/:id/:transaction_id/delete' => 'carpool#delete_transaction' , as: :borrar_transaccion

  devise_for :users,  :controllers => { :omniauth_callbacks => 'omniauth_callbacks', :registrations => "registrations"  }, :skip => [:sessions, :passwords, :confirmations, :registrations]
  as :user do
    get   '/registrarse' => 'registrations#new',    :as => :new_user_registration
    post  '/registrarse' => 'registrations#create', :as => :user_registration

    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    match 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session,
      :via => Devise.mappings[:user].sign_out_via

    scope '/account' do
      get   '/resetpassword'        => 'devise/passwords#new',    :as => :new_user_password
      put   '/resetpassword'        => 'devise/passwords#update', :as => :user_password
      post  '/resetpassword'        => 'devise/passwords#create'
      get   '/resetpassword/change' => 'devise/passwords#edit',   :as => :edit_user_password

      get   '/confirm'        => 'devise/confirmations#show',   :as => :user_confirmation
      post  '/confirm'        => 'devise/confirmations#create'
      get   '/confirm/resend' => 'devise/confirmations#new',    :as => :new_usern_confirmation

      get '/cancel'   => 'registrations#cancel', :as => :cancel_user_registration
      get '/settings' => 'registrations#edit',   :as => :edit_user_registration
      post '/settings' => 'registrations#update', :as => :update_user_registration

      delete '' => 'devise/registrations#destroy'
    end
  end

  devise_for :publicadors, :skip => [:sessions, :passwords, :confirmations, :registrations]
  as :publicador do
    get 'cv-login' => 'devise/sessions#new', :as => :new_publicador_session
    post 'cv-login' => 'devise/sessions#create', :as => :publicador_session
    match 'cv-logout' => 'devise/sessions#destroy', :as => :destroy_publicador_session,
      :via => Devise.mappings[:publicador].sign_out_via
  end

  authenticated :user do
    root :to => "evento#eventos", as: "authenticated_root"
  end

  authenticated :publicador do
    root :to => "admin/dashboard#index", as: "authenticated_publicador_root"
  end

  root :to => 'index#index'

end

web/app/models/ranking.rb
class Ranking < ActiveRecord::Base

	#Notificaciones
	include PublicActivity::Common

	#Relaciones
	belongs_to :user
	belongs_to :owner_id, :class_name => "User", :foreign_key => "user_id"
end

web/app/controllers/rankings_controller.rb
class RankingsController < ApplicationController
  before_action :set_ranking, only: [:show, :edit, :update, :destroy]

  # GET /rankings
  # GET /rankings.json
  def index
    @rankings = Ranking.all
  end

  # GET /rankings/1
  # GET /rankings/1.json
  def show
  end

  # GET /rankings/new
  def new
    @ranking = Ranking.new
  end

  # GET /rankings/1/edit
  def edit
    ranking = Ranking.find(params[:id])
    @user = User.find(ranking.user_id)
  end

  # POST /rankings
  # POST /rankings.json
  def create
    @ranking = Ranking.new(ranking_params)

    respond_to do |format|
      if @ranking.save
        format.html { redirect_to @ranking }
        format.json { render :show, status: :created, location: @ranking }
      else
        format.html { render :new }
        format.json { render json: @ranking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rankings/1
  # PATCH/PUT /rankings/1.json
  def update
    respond_to do |format|
      if @ranking.update(ranking_params)
        format.html { redirect_to @ranking, notice: 'Ranking was successfully updated.' }
        format.json { render :show, status: :ok, location: @ranking }
      else
        format.html { render :edit }
        format.json { render json: @ranking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rankings/1
  # DELETE /rankings/1.json
  def destroy
    @ranking.destroy
    respond_to do |format|
      format.html { redirect_to rankings_url, notice: 'Ranking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ranking
      @ranking = Ranking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ranking_params
      params.require(:ranking).permit(:value, :comment, :assist, :driver, :user_id, :owner_id)
    end
end

web/app/helpers/rankings_helper.rb
module RankingsHelper
end

web/app/views/rankings/_form.html.erb
  <%= simple_form_for(@ranking) do |f| %>
    <%= f.error_notification %>
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="form-inputs">
          <div class="row">
            <h3>¿Asistió al evento utilizando el carpool?</h3>
            <%= f.check_box :assist, :onchange=> "abrirCampos();", :class=> "form-control"  %> 
            <h4 class="pull-right">(Clickear si asistió)</h4>
          </div>
          
          <div class="row">
          <h3><%= f.label "Valoración" %></h3>
            <div class="text-center">
              <input type="hidden" class="rating" name="ranking[value]" id="ranking_value" disabled= "disabled" data-start="1" data-stop="6"/>
              <span id="cantidad"> 0 </span> Estrellas
            </div>
          </div>
          <div class="row">
          <h3><%= f.label "Dejale un comentario!" %></h3>
          <%= f.text_area :comment, :disabled=> "disabled", :class=> "form-control" %>
          </div>
        </div>

        <div class="form-actions">
          <%= f.submit "Enviar Valoración", :class => "btn btn-primary btn-block" %>
        </div>
      </div>  
    </div>
  <% end %>
<script type="text/javascript" src="bootstrap-rating.js"></script>

web/app/views/rankings/edit.html.erb
<div class="container">

	<div class="col-md-5 col-md-offset-4">
		<h1>Evalúa a <%= @user.nombre %> </h1>

		<%= render 'form' %>
	</div>

</div>

<script type="text/javascript">
function abrirCampos(){
	var check = $("#ranking_assist").is(':checked');

	if(check){
		$(".rating-symbol").css("color", "orange");
		$("#ranking_value").prop('disabled', false);
		$("#ranking_comment").prop('disabled', false);
	}
	else{
		$(".rating-symbol").css("color", "grey");
		$("#ranking_value").prop('disabled', true);
		$("#ranking_comment").prop('disabled', true);
		$("#ranking_value").val(0);
		$("#cantidad").html($("#ranking_value").val());
		$("#ranking_comment").val("");
	}
}

$('#ranking_value').on('change', function () {
  $("#cantidad").html($("#ranking_value").val());
});

</script>

web/app/views/rankings/index.html.erb
<h1>Listing rankings</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th>Comment</th>
      <th>Assist</th>
      <th>Driver</th>
      <th>User</th>
      <th>Owner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rankings.each do |ranking| %>
      <tr>
        <td><%= ranking.value %></td>
        <td><%= ranking.comment %></td>
        <td><%= ranking.assist %></td>
        <td><%= ranking.driver %></td>
        <td><%= ranking.user %></td>
        <td><%= ranking.owner_id %></td>
        <td><%= link_to 'Show', ranking %></td>
        <td><%= link_to 'Edit', edit_ranking_path(ranking) %></td>
        <td><%= link_to 'Destroy', ranking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ranking', new_ranking_path %>

web/app/views/rankings/new.html.erb
<h1>New ranking</h1>

<%= render 'form' %>

<%= link_to 'Back', rankings_path %>

web/app/views/rankings/show.html.erb
<div class="container">
<h1 class="page-header">Gracias por responder</h1>
  <div class="col-md-5 col-md-offset-4">
    <div class="panel panel-default">
      <% if @ranking.assist %>
        <div class="panel-heading">
          <h2 class="panel-title">Respuestas</h2>
        </div>
        <div class="panel-body">
          <div >
            <h3>Valoración:</h3>
            <style type="text/css">
              .rating-symbol{
                color:orange;
              }
            </style>
            <input type="hidden" class="rating" readonly= "true" data-start="1" data-stop="6" value="<%= @ranking.value %>"/> 
          </div>
          <hr>
          <div >
            <h3>Comentario:</h3>
            <%= @ranking.comment %>
          </div>
        </div>
      <% else %>
      <h1>Gracias por responder</h1>
      <% end %>
  </div>
  </div>
</div>