web/config/routes.rb
Rails.application.routes.draw do

  get '/feriadesoftware' => redirect('http://feriadesoftware.cl')
  get '/informatica' => redirect('http://inf.utfsm.cl')
  get '/facebook' => redirect('https://www.facebook.com/Carryvent')
  get '/usm' => redirect('http://www.usm.cl')
  ActiveAdmin.routes(self)
  resources :rankings
  resources :comments, :only =>[:create, :destroy]

  resources :notifications
  get '/checkNewNotification' => "notifications#checking_new" , as: :checking_new

  get '/eventos' => 'evento#eventos', as: :lista_eventos_user
  get '/evento/:id' => 'evento#show', as: :mostrar_evento
  get '/operario/list_eventos' => "evento#list_eventos", as: :list_eventos
  get '/operario/ruta_evento/:id' => "evento#ruta_evento", as: :ruta_evento

  get '/evento/:id/reserva' => "pasajes#reserva", as: :reserva_pasaje
  post '/evento/:id/reserva' => "pasajes#reserva_send", as: :crear_reserva
  get '/evento/:id/reservado' => "pasajes#reservado", as: :pasaje_reservado
  post '/reserva/concretar/:id' => "pasajes#aceptar_reserva", as: :concretar_reserva
  get '/operario/list_pasajes/:id' => "pasajes#list_pasajes", as: :list_pasajes

  get '/user/:id' => 'user#perfil', as: :perfil_user
  get '/user/:id/editar' => 'user#editar', as: :editar_user

  get 'evento/:evento_id/carpool/publicar' => 'carpool#publicar', as: :publicar_carpool
  post 'evento/:evento_id/carpool/publicar' =>  'carpool#new', as: :new_publicar_carpool
  get 'evento/:evento_id/carpool/:id' => 'carpool#show', as: :mostrar_carpool
 
  post 'evento/:evento_id/carpool/:id' => 'carpool#new_transaction', as: :crear_transaccion_carpool
  get 'evento/carpool/:evento_id/:id/:transaction_id/accept' => 'carpool#aceptar_transaction', as: :aceptar_transaccion
  get 'evento/carpool/:evento_id/:id/:transaction_id/reject' => 'carpool#rechazar_transaction', as: :rechazar_transaccion
  get 'evento/carpool/:evento_id/:id/:transaction_id/delete' => 'carpool#delete_transaction' , as: :borrar_transaccion

  devise_for :users,  :controllers => { :omniauth_callbacks => 'omniauth_callbacks', :registrations => "registrations"  }, :skip => [:sessions, :passwords, :confirmations, :registrations]
  as :user do
    get   '/registrarse' => 'registrations#new',    :as => :new_user_registration
    post  '/registrarse' => 'registrations#create', :as => :user_registration

    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    match 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session,
      :via => Devise.mappings[:user].sign_out_via

    scope '/account' do
      get   '/resetpassword'        => 'devise/passwords#new',    :as => :new_user_password
      put   '/resetpassword'        => 'devise/passwords#update', :as => :user_password
      post  '/resetpassword'        => 'devise/passwords#create'
      get   '/resetpassword/change' => 'devise/passwords#edit',   :as => :edit_user_password

      get   '/confirm'        => 'devise/confirmations#show',   :as => :user_confirmation
      post  '/confirm'        => 'devise/confirmations#create'
      get   '/confirm/resend' => 'devise/confirmations#new',    :as => :new_usern_confirmation

      get '/cancel'   => 'registrations#cancel', :as => :cancel_user_registration
      get '/settings' => 'registrations#edit',   :as => :edit_user_registration
      post '/settings' => 'registrations#update', :as => :update_user_registration

      delete '' => 'devise/registrations#destroy'
    end
  end

  devise_for :publicadors, :skip => [:sessions, :passwords, :confirmations, :registrations]
  as :publicador do
    get 'cv-login' => 'devise/sessions#new', :as => :new_publicador_session
    post 'cv-login' => 'devise/sessions#create', :as => :publicador_session
    match 'cv-logout' => 'devise/sessions#destroy', :as => :destroy_publicador_session,
      :via => Devise.mappings[:publicador].sign_out_via
  end

  authenticated :user do
    root :to => "evento#eventos", as: "authenticated_root"
  end

  authenticated :publicador do
    root :to => "admin/dashboard#index", as: "authenticated_publicador_root"
  end

  root :to => 'index#index'

end

web/app/controllers/carpool_controller.rb
class CarpoolController < ApplicationController

  #Restringiendo usuarios no conectados solo a ver carpool
	before_filter :authenticate_user!, :except => [:show]

  add_breadcrumb "Inicio", :root_path
  add_breadcrumb "Eventos", :lista_eventos_user_path

  #######################
  # Publicar y mostrar  #
  #######################

	#Vista de publicar carpool
	def publicar
    evento = Evento.find(params[:evento_id])
    add_breadcrumb evento.name, mostrar_evento_path(evento)
    add_breadcrumb "Publicar", :publicar_carpool_path
    
		@publicacioncarpool = PublicacionCarpool.new
	end

	#Crear una nueva publicacion de carpool
	def new
		#Generamos user_evento y lo guardamos
		userEvento = current_user.user_eventos.new(:evento_id => params[:evento_id])
		
    #Se guarda el user_evento
		if userEvento.save
		#falta limitar 1 publicacion por usuario
			publicacionCarpool = PublicacionCarpool.new(carpool_params.merge(:user_evento_id => userEvento.id))
			
			#Vemos si se guardo correctamente
			if publicacionCarpool.save
				redirect_to mostrar_carpool_path(params[:evento_id],publicacionCarpool)
			else
				userEvento.destroy
				redirect_to publicar_carpool_path(params[:evento_id])
			end
		else
      redirect_to publicar_carpool_path(params[:evneto_id])
		end
	end

  #Editar carpool
	def update
		publicacionCarpool = PublicacionCarpool.find(params[:id])
		publicacionCarpool.update(carpool_params)
	end

	#Mostramos todo lo relevante a la publicacion carpool
	def show
    evento = Evento.find(params[:evento_id])
    add_breadcrumb evento.name, mostrar_evento_path(evento)
    add_breadcrumb "Carpool", :mostrar_carpool_path

		@evento = Evento.find(params[:evento_id])
		@carpool = PublicacionCarpool.find(params[:id])
		@userPub = User.joins(user_eventos: [:user, :evento, :publicacion_carpool]).where(publicacion_carpools: {id: params[:id]}).first
    
    #Contando asientos libres
    asientosTomados = @carpool.transaccion_carpools.where(:aceptado => true).count
    @asientosDisp = @carpool.asientos_disp - asientosTomados
    
    #Comentarios
    @comments = @carpool.comment_threads.order('created_at desc')
    @new_comment = Comment.build_from(@carpool, current_user.id, "")

    if @userPub != current_user
      @transUser = @carpool.transaccion_carpools.where(:user_id => current_user.id).first
    else
      @peticiones = @carpool.transaccion_carpools
    end

    @transaccion = TransaccionCarpool.new
  end

  ########################
  #     Transacciones    # 
  ########################


    #Creando nueva peticion
   	def new_transaction
   		evento = Evento.find(params[:evento_id])
   		carpool = PublicacionCarpool.find(params[:id])
   		#Usuario que pide el carpool
   		user = current_user
   		#Usuario que publico el carpool
   		userPub = User.joins(user_eventos: [:user, :evento, :publicacion_carpool]).where(publicacion_carpools: {id: params[:id]}).first
   		
      if user != userPub
   			trans = user.transaccion_carpools.new(:asientos => trans_carpool_params["asientos"],  :publicacion_carpool_id => carpool.id , :aceptado => nil)

   			if trans.save
   				#Se crea la notificacion
   				trans.create_activity :create, owner: current_user, recipient: carpool.user_evento.user, parameters: {asientos: trans_carpool_params["asientos"] , publicacion_carpool_id: carpool.id  }
   				##MOSTRAR QUE SE PUDO CREAR
   				redirect_to mostrar_carpool_path(evento, carpool)
   			else
   				#MOSTRAR ERROR QUE NO SE PUDO CREAR
   				redirect_to mostrar_carpool_path(evento, carpool)
   			end
      else
        redirect_to mostrar_carpool_path(evento,carpool)
   		end
   	end

    #Aceptar peticion
   	def aceptar_transaction

   		transaccion = TransaccionCarpool.find(params[:transaction_id])
   		evento = Evento.find(params[:evento_id])
   		carpool = PublicacionCarpool.find(params[:id])
   		
      #Se cambia el valor de la transaccion a aceptado
      # y se crea la respectiva notificacion
      aceptar = transaccion.update(:aceptado => true)
   		transaccion.create_activity :aceptado, owner:current_user , recipient:transaccion.user , parameters: {asientos: transaccion.asientos , publicacion_carpool_id: carpool.id  }
   	  
      #Creamos la encuesta que será "enviada" despues de la hora y fecha del carpool
      scheduler = Rufus::Scheduler.new
    
      if carpool.date_time < DateTime.current
        fecha = DateTime.current + 1.minutes
      else 
        fecha = carpool.date_time
      end
        job_id = scheduler.in fecha.to_s do
        #Creamos las encuestas
        encuestaUser = Ranking.new(driver: false, user_id:carpool.user_evento.user , owner_id:transaccion.user)
        encuestaPub = Ranking.new(driver: true, user_id: current_user, owner_id: carpool.user_evento.user)
        encuestaUser.save
        encuestaPub.save
        #Creamos las notificaciones
        encuestaUser.create_activity :created, owner: transaccion.user, recipient: carpool.user_evento.user
        encuestaPub.create_activity :created, owner: carpool.user_evento.user,  recipient: transaccion.user
       end
       #Guardamos la id del scheduler
       transaccion.update(:job_id => job_id)

      redirect_to mostrar_carpool_path(evento,carpool)
    end

    #Rechazar peticion
   	def rechazar_transaction
   		transaccion = TransaccionCarpool.find(params[:transaction_id])
   		evento = Evento.find(params[:evento_id])
   		carpool = PublicacionCarpool.find(params[:id])

      #Cambiamos el estado de la transaccion a rechazado y
      # se crea una notificacion diciendo que se rechazo
   		rechazar = transaccion.update(:aceptado => false)
   		transaccion.create_activity :rechazado, owner:current_user , recipient:transaccion.user, parameters: {asientos:transaccion.asientos , publicacion_carpool_id: carpool.id  }
   	  
      #Buscamos si existe un trabajo relacionado a la transaccion
      scheduler = Rufus::Scheduler.new
      job = scheduler.job(transaccion.job_id)
      if job
        job.unschedule
      end 
      redirect_to mostrar_carpool_path(evento,carpool)
    end

    #Borrar transaccion
   	def delete_transaction
		  transaccion = TransaccionCarpool.find(params[:transaction_id])
   		evento = Evento.find(params[:evento_id])
   		carpool = PublicacionCarpool.find(params[:id])

      #Se borra la transaccion
   		borrar = transaccion.destroy
   		transaccion.create_activity :borrado, owner:current_user , recipient:transaccion.user, parameters: {asientos: transaccion.asientos , publicacion_carpool_id: carpool.id  }
   	  
      redirect_to mostrar_carpool_path(evento,carpool)
    end

    #Editar asientos de peticion
   	def cambiar_asientos
   		transaccion = TransaccionCarpool.find(params[:transaction_id])
   		evento = Evento.find(params[:evento_id])
   		carpool = PublicacionCarpool.find(params[:id])
      
      #Vemos si el usuario que mando la peticion es el mismo que la creo
      if current_user == transaccion.user.id
   		 cambiar = transaccion.update(:asientos => params[:asientos])
   		 transaccion.create_activity :updated, owner: current_user, recipient: carpool.user_evento.user, parameters: {asientos: trans_carpool_params["asientos"] , publicacion_carpool_id: carpool.id  }
   	  end
    end

    #Tomamos solamente los parametros que sirven para publicacion_carpool
	private
	  def carpool_params
	    params.require(:publicacion_carpool).permit(:user_evento_id, :fecha, :descripcion, :hora_desde, :desde , :asientos_disp, :tipo_vehiculo, :celular)
	  end

	  def trans_carpool_params
	  	params.require(:transaccion_carpool).permit(:asientos)
	  end
end

web/app/helpers/carpool_helper.rb
module CarpoolHelper
end

web/app/views/carpool/publicar.html.erb
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places"></script>
<style type="text/css">
  .error-carpool{
    color:#FF0000; 
  }
</style>
<% title "Publicar Carpool" %>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <h2 class="page-header">Publicar Carpool</h2>
      <ol class="breadcrumb">
        <%= render_breadcrumbs :tag => :li, :separator => "" %>
      </ol>
      <div class="account-wall_reg">
    <%= form_for @publicacioncarpool, url: new_publicar_carpool_path  do |f| %>

        <% if @publicacioncarpool.errors.any? %>
        <div class="row" style="padding-top:0px;">
          <div id="error_explanation">
            <h2>
              <%= pluralize(@publicacioncarpool.errors.count, "error") %> prohibited
              this article from being saved:
            </h2>
            <ul>
              <% @publicacioncarpool.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>
      <div class="row">
          <div class="field col-md-6">
            <%= f.label "Fecha de Salida" %> <br>
            <%= f.text_field :fecha, :readonly=> "true" %>
          </div>
          <div class="field col-md-6">
            <%= f.label "Hora Aproximada de Salida" %><br>
            <%= f.text_field :hora_desde, :class => "form-control" %>
          </div>
      </div>
      <div class="row">
        <div class="field col-md-12">
          <%= f.label "Lugar de Salida" %>
          <%= f.text_field :desde , :class => "form-control", :onFocus=> "geolocate()", :placeholder => "ej: Calle, Número, Ciudad, Pais" %>
        </div>
      </div>
      <div class="row">
        <div class="field col-md-6 ">
          <%= f.label "Tipo de Vehículo" %>
          <%= f.select :tipo_vehiculo, options_for_select([["Sedan","Sedan"], ["Camioneta","Camioneta"], ["Minibus","Minibus"]]),{include_blank: false}, {class: "form-control", onchange: "maxLibres();"}%>
        </div>
        <div class="field col-md-6">
          <%= f.label "Asientos Disponibles" %><br>
          <div class="text-center">
            <%= f.select :asientos_disp, ((1..3).map {|i| [i,i]}), {}, {style: "width: 60px;", class: "form-control"}  %>
          </div>    
        </div>
      </div>
         <div class="field">
          <%= f.label "Celular de contacto" %>
          <%= f.text_field :celular , :class => "form-control", :placeholder => "ej: +5699999999" %>
        </div>
        <div class="field">
          <%= f.label "Descripción" %><br>
          <%= f.text_area :descripcion , :class => "form-control" %>
        </div>

        <div class="actions">
          <%= f.submit "Crear Publicación carpool", :class => "btn btn-primary btn-block", :onClick=> "validate()" %>
        </div>
    
    <% end %>
    </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  function maxLibres(){
    var tipo = $("#publicacion_carpool_tipo_vehiculo option:selected").text();

    var select = $("#publicacion_carpool_asientos_disp");
    select.empty();
    switch(tipo){
      case("Sedan"):
        <% (1..3).each do |i| %> 
          select.append('<option value="<%= i %>"><%= i %></option>');
        <% end %>
        break;
      case("Camioneta"):
        <% (1..2).each do |i| %>
          select.append('<option value="<%= i %>"><%= i %></option>');
        <% end %>
        break;
      case("Minibus"):
        <% (1..7).each do |i| %>
          select.append('<option value="<%= i %>"><%= i %></option>');
        <% end %>
        break;
    
    }
  }
  
  $(function() {
    $("#publicacion_carpool_fecha").datepicker();
  });
  $(function() {
    $("#publicacion_carpool_hora_desde").timepicker({ timeFormat: 'H:i', defaultTime: new Date() });
  });


  function optioner(){
      $("#mini_hora").timepicker('option',{useSelect: true});
  }

// This example displays an address form, using the autocomplete feature
// of the Google Places API to help users fill in the information.

var placeSearch, autocomplete;

function initialize() {

  // Create the autocomplete object, restricting the search
  // to geographical location types.
  autocomplete = new google.maps.places.Autocomplete(
      /** @type {HTMLInputElement} */(document.getElementById('publicacion_carpool_desde')),
      { types: ['geocode'] });
  // When the user selects an address from the dropdown,
  // populate the address fields in the form.
  google.maps.event.addListener(autocomplete);
}

// Bias the autocomplete object to the user's geographical location,
// as supplied by the browser's 'navigator.geolocation' object.
function geolocate() {
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(function(position) {
      var geolocation = new google.maps.LatLng(
          position.coords.latitude, position.coords.longitude);
      autocomplete.setBounds(new google.maps.LatLngBounds(geolocation,
          geolocation));
    });
  }
}
$(document).ready(function(){
  initialize();
  $("#new_publicacion_carpool").validate({
    errorClass: "error-carpool",
    rules: {
        "publicacion_carpool[fecha]": {required: true},
        "publicacion_carpool[hora_desde]": {required: true},
        "publicacion_carpool[desde]": {required: true},
        "publicacion_carpool[tipo_vehiculo]": {required: true},
        "publicacion_carpool[asientos_disp]":{required: true},
        "publicacion_carpool[celular]": {required: true},
        "publicacion_carpool[descripcion]": {required: true}
    }
  });
});

function validate(){
  if(!($("#new_publicacion_carpool").valid())){
    event.preventDefault();
  }
}

</script>

web/app/views/carpool/show.html.erb
<% title "Carpool" %>

<% content_for :head do %>
  <meta property="og:title" content="Revisa mi publicación Carpool a <%= @evento.name %>"/>
  <meta property="og:site_name" content="www.carryvent.cl"/>
  <meta property="fb:app_id" content="749613061749643"/>
  <meta property="og:image" content="<%= request.host + @evento.image.url%>">
  <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<% end %>


<style type="text/css">
    .row{
        padding-top:0;
    }

</style>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/es_LA/sdk.js#xfbml=1&appId=749613061749643&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));

</script>


<div class="container">

    <!-- Breadcrumb -->
      <h2 class="page-header"> Carpool hacia <%= @evento.name %></h2>
      <ol class="breadcrumb">
        
        <%= render_breadcrumbs :tag => :li, :separator => "" %>
      </ol>



    <div class="row">
        <div class="col-md-6">
            
            <h4>Publicador del Carpool</h4>
            <div class="col-md-2 col-xs-4">
              
                <% if @userPub.foto.present? %> 
                  <img class="img-square img-responsive img-center" src="<%= @userPub.foto.url %>" width="80" height="80" alt=""> 
                <% else %>  
                  <img class="img-square img-responsive img-center" src="http://sintoniageek.com/wp-content/uploads/2011/03/avatar-facebook-defecto1.jpg" width="80" height="80" alt="">
                <% end %>

            </div>

            <div class="col-md-10 col-xs-8">
              <p><b>Nombre Usuario: </b><%= @userPub.nombre %> </p>
              <% if @userPub.city %>
                <p>
                  <b>Ciudad: </b><%= @userPub.ciudad_region %>
                </p>
              <% end %>
              <p>
                <b>Correo: </b><%= @userPub.email %> 
              </p>

              <% if @transUser and @transUser.aceptado %>
                <strong>¡Contacta al publicador!</strong>
                <p style="color:red;"><b>Celular de contacto: <%= @carpool.celular %> </b> </p>
              <% end %>
              <p>
                <b>Comparte la publicación en Facebook</b><br>
                <div class="fb-share-button" data-href="<%=request.original_url %>" data-layout="button_count"></div>
              </p>  

            </div>

        <h4>Evento del Carpool</h4>
            <div class="col-md-2 col-xs-4">

              <img class="img-square img-responsive img-center" 
              src="<% if ! @evento.image.nil? %>
              <%= @evento.image %>
              <% else %>
              http://placehold.it/150x150
              <%end%>" 
              width="80" height="80" alt="">
            </div>
            <div class="col-md-10 col-xs-8">
              <p><b>Nombre Evento: </b><%= @evento.name %> </p>
              <p><b>Fecha: </b><%= @evento.date %></p>
              <p><b>Lugar: </b><%= @evento.address %> </p>
            </div><!--Evento-->
        </div><!-- col-md-6 -->


        <div class="col-md-6">
          <div class="row">
            <h4>Lugar de Salida</h4>
                <div id="map"></div>     
          </div>  
        </div><!-- col-md-6-->
    </div>



    <div class="row">
        <div class="col-md-6">
            <% if @userPub != current_user %>
                    <h4>Únete al Carpool!</h4>
                        <p><b>Lugar de Salida: </b> <%= @carpool.desde %></p>
                        <p><b>Hora: </b> <%= @carpool.hora_desde.strftime("%H:%M") %></p>
                        <p><b>Asientos disponibles:</b> <span class="badge"><%= @asientosDisp %></span></p>
                        <p><b>Descripción: <%= @carpool.descripcion %></b> </p>
                    <% if @transUser %>
                        <div class="text-center">
                            Su petición fue 
                            <% if @transUser.aceptado.nil? %>
                               <span style="color:blue;">Enviada</span>
                            <% elsif @transUser.aceptado %>
                               <span style="color:green;">Aceptada</span> 
                            <% else %>
                               <span style="color:red;">Rechazada</span> 
                            <% end %>
                        </div>
                    <% else %>
                    <div class="panel peticiones-container col-xs-offset-1">
                      <b> Pedir asientos en carpool </b>
                      <%= form_for @transaccion , url: crear_transaccion_carpool_path do |f| %>
                          <%= f.label :asientos %>
                          <%= f.select :asientos, ((1..@asientosDisp).map {|i| [i,i] }), :class=>"form-control" %> <br>
                          <%= f.submit "Realizar petición", :class =>"btn btn-primary"%>
                      <%end%>
                    </div>
                    <%end%>

            <% else %>
              <div class="row">
                  <div class="publicacion-container panel" style="margin:5px 5px 5px 5px;">
                    <div class="text-center">
                          <b>Asientos disponibles:</b> <span class="badge"><%= @asientosDisp %></span>
                    </div>
                  <% if !@peticiones.nil? %>
                    <table class="table table-striped">
                        <tr>
                        <th> Usuario </th>
                        <th> Ciudad </th>
                        <th> N° de Asientos </th>
                        <th>  Estado </th>
                        <th>  Aceptar/Rechazar</th>
                        </tr>

                      <% @peticiones.each do |peticion| %>
                        <tr>
                          <td>
                            <% if peticion.user.foto.thumb.url %>
                             <% img = peticion.user.foto.thumb.url %>
                             <img src="<%= img  %>" alt="" class="img-circle">
                            <% else %>
                              <img src="/assets/place_user.png", class="img-circle", style="width:30px;heigh:30px">
                            <% end %>
                            <%= link_to peticion.user.nombre[0..20]+"..", perfil_user_path(peticion.user) %>
                          </td>
                          <td>
                            <% if peticion.user.city %>
                              <%= peticion.user.city.name %>
                            <% end %>
                          </td>
                          <td>
                            <%= peticion.asientos%>
                          </td>
                          <td>
                            <% if peticion.aceptado.nil? %>
                              <span style="color:blue;">Pendiente</span>
                            <% elsif peticion.aceptado %>
                              <span style="color:green;">Aceptado</span>
                            <% else %>
                              <span style="color:red;">Rechazado</span>
                            <% end %>
                          </td>
                          <td>
                            <% if peticion.aceptado %>
                                <span class="glyphicon glyphicon-ok" style="color:grey;"></span>
                            <% else %>
                            <%= link_to aceptar_transaccion_path(@evento, @carpool, peticion) do 
                            %> 
                            <span class="glyphicon glyphicon-ok" style="color:green;"></span>
                            <% end %>
                            / 
                            <% if peticion.aceptado == false %>
                              <span class="glyphicon glyphicon-remove" style="color:grey;"></span>
                            <% else %>
                              <%= link_to rechazar_transaccion_path(@evento, @carpool, peticion) do %>
                              <span class="glyphicon glyphicon-remove" style="color:red;"></span> 
                            <%end%>
                          </td>
                        </tr>
                      <% end %>
                  <% end %>
                <% end %>
                 </table> 
              <% end %>
              </div>
            </div>
            <% end %>
            </div>
            <div class="col-md-6">
                <div class="row">
                  <div  class="panel comment-container" >
                      <h4>Deja tus consultas y comentarios</h4>
                      <div class="comments">
                        <div class="first-comment"></div>
                          <%= render :partial => 'comments/comment', :collection => @comments, :as => :comment %>
                      </div>
                      <div class="comment-send"> 
                          <%= render :partial => 'comments/form', :locals => { :comment => @new_comment } %>
                      </div>
                  </div>
                </div>

            </div>
        </div>


    </div>

</div>



<script type="text/javascript">

      function seleccionar(numero) {
    for (var i = 1; i <= 9; i++) {
      if (i == numero){
        document.getElementById('asiento'+i).src = "/assets/asientoSeleccionado.png";
      }
      else{
        document.getElementById('asiento'+i).src = "/assets/asientoSinSeleccionar.png";
      }
    }
  }
                     
  var geocoder = new google.maps.Geocoder();
  var address = "<%= @carpool.desde %>";
                     
  geocoder.geocode( { 'address': address}, function(results, status) {
                     
      if (status == google.maps.GeocoderStatus.OK) {
          var latitude = results[0].geometry.location.lat();
          var longitude = results[0].geometry.location.lng();
          
          var directionsDisplay = new google.maps.DirectionsRenderer();
          var directionsService = new google.maps.DirectionsService();

          function calcRoute(origLat,origLong, destLat, destLong) {
            var origin      = new google.maps.LatLng(origLat, origLong);
            var destination = new google.maps.LatLng(destLat, destLong);
            var request = {
                origin:      origin,
                destination: destination,
                travelMode:  google.maps.TravelMode.DRIVING
            };
            directionsService.route(request, function(response, status) {
              if (status == google.maps.DirectionsStatus.OK) {
                directionsDisplay.setDirections(response);
              }
            });
          }

          calcRoute(latitude, longitude, <%= @evento.latitude %>, <%= @evento.longitude %>);




          var handler = Gmaps.build('Google');
          handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
            markers = handler.addMarkers([{"lat":latitude,"lng":longitude,"infowindow":"Lugar de Salida","name":"Lollapalooza"}]);
            handler.bounds.extendWith(markers);
            handler.fitMapToBounds();
            handler.getMap().setZoom(14);
            directionsDisplay.setMap(handler.getMap());
          });
          
       }
   });
</script>