web/config/routes.rb
Rails.application.routes.draw do

  get '/feriadesoftware' => redirect('http://feriadesoftware.cl')
  get '/informatica' => redirect('http://inf.utfsm.cl')
  get '/facebook' => redirect('https://www.facebook.com/Carryvent')
  get '/usm' => redirect('http://www.usm.cl')
  ActiveAdmin.routes(self)
  resources :rankings
  resources :comments, :only =>[:create, :destroy]

  resources :notifications
  get '/checkNewNotification' => "notifications#checking_new" , as: :checking_new

  get '/eventos' => 'evento#eventos', as: :lista_eventos_user
  get '/evento/:id' => 'evento#show', as: :mostrar_evento
  get '/operario/list_eventos' => "evento#list_eventos", as: :list_eventos
  get '/operario/ruta_evento/:id' => "evento#ruta_evento", as: :ruta_evento

  get '/evento/:id/reserva' => "pasajes#reserva", as: :reserva_pasaje
  post '/evento/:id/reserva' => "pasajes#reserva_send", as: :crear_reserva
  get '/evento/:id/reservado' => "pasajes#reservado", as: :pasaje_reservado
  post '/reserva/concretar/:id' => "pasajes#aceptar_reserva", as: :concretar_reserva
  get '/operario/list_pasajes/:id' => "pasajes#list_pasajes", as: :list_pasajes

  get '/user/:id' => 'user#perfil', as: :perfil_user
  get '/user/:id/editar' => 'user#editar', as: :editar_user

  get 'evento/:evento_id/carpool/publicar' => 'carpool#publicar', as: :publicar_carpool
  post 'evento/:evento_id/carpool/publicar' =>  'carpool#new', as: :new_publicar_carpool
  get 'evento/:evento_id/carpool/:id' => 'carpool#show', as: :mostrar_carpool
 
  post 'evento/:evento_id/carpool/:id' => 'carpool#new_transaction', as: :crear_transaccion_carpool
  get 'evento/carpool/:evento_id/:id/:transaction_id/accept' => 'carpool#aceptar_transaction', as: :aceptar_transaccion
  get 'evento/carpool/:evento_id/:id/:transaction_id/reject' => 'carpool#rechazar_transaction', as: :rechazar_transaccion
  get 'evento/carpool/:evento_id/:id/:transaction_id/delete' => 'carpool#delete_transaction' , as: :borrar_transaccion

  devise_for :users,  :controllers => { :omniauth_callbacks => 'omniauth_callbacks', :registrations => "registrations"  }, :skip => [:sessions, :passwords, :confirmations, :registrations]
  as :user do
    get   '/registrarse' => 'registrations#new',    :as => :new_user_registration
    post  '/registrarse' => 'registrations#create', :as => :user_registration

    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    match 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session,
      :via => Devise.mappings[:user].sign_out_via

    scope '/account' do
      get   '/resetpassword'        => 'devise/passwords#new',    :as => :new_user_password
      put   '/resetpassword'        => 'devise/passwords#update', :as => :user_password
      post  '/resetpassword'        => 'devise/passwords#create'
      get   '/resetpassword/change' => 'devise/passwords#edit',   :as => :edit_user_password

      get   '/confirm'        => 'devise/confirmations#show',   :as => :user_confirmation
      post  '/confirm'        => 'devise/confirmations#create'
      get   '/confirm/resend' => 'devise/confirmations#new',    :as => :new_usern_confirmation

      get '/cancel'   => 'registrations#cancel', :as => :cancel_user_registration
      get '/settings' => 'registrations#edit',   :as => :edit_user_registration
      post '/settings' => 'registrations#update', :as => :update_user_registration

      delete '' => 'devise/registrations#destroy'
    end
  end

  devise_for :publicadors, :skip => [:sessions, :passwords, :confirmations, :registrations]
  as :publicador do
    get 'cv-login' => 'devise/sessions#new', :as => :new_publicador_session
    post 'cv-login' => 'devise/sessions#create', :as => :publicador_session
    match 'cv-logout' => 'devise/sessions#destroy', :as => :destroy_publicador_session,
      :via => Devise.mappings[:publicador].sign_out_via
  end

  authenticated :user do
    root :to => "evento#eventos", as: "authenticated_root"
  end

  authenticated :publicador do
    root :to => "admin/dashboard#index", as: "authenticated_publicador_root"
  end

  root :to => 'index#index'

end

web/app/models/user.rb
class User < ActiveRecord::Base
  #Para request
  require 'net/http'
  require "uri"

  #Para last_checked
  before_create :timestamp

  #Para subir fotos
  mount_uploader :foto, FotoUploader


  acts_as_messageable
  #Comprobar si el email es valido
  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :authentication_keys => [:email]

  devise :omniauthable, :omniauth_providers => [:facebook, :twitter]

#  before_action :set_user, :finish_signup

  validates :email, presence: true
  validates :nombre, presence: true
  #validates :ciudad, presence: true

  #Relaciones
  has_many :red_socials
  has_many :transaccion_carpools
  
  has_many :user_eventos
  has_many :eventos , through: :user_eventos
  has_many :publicacion_carpools, through: :user_eventos
  has_many :reservas, through: :user_eventos


  has_many :gustos
  has_many :categories, through: :gustos

  has_many :rankings

  belongs_to :city
  belongs_to :region


  def ranking
    sum = self.rankings.sum(:value,  :conditions => {:assist => true})
    if sum
      return sum
    else
      return 0
    end
  end


  def ciudad_region
    ciudadRegion = ""
    if self.city
      ciudadRegion += self.city.name + " "
    end

    if self.region
      ciudadRegion += self.region.name
    end
    return ciudadRegion

  end
  def self.find_for_oauth(auth, signed_in_resource = nil)
    # Get the identity and user if they exist
    identity = RedSocial.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          nombre: auth.extra.raw_info.name,
          #username: auth.info.nickname || auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20],
          direccion: auth.info.location
        )

        access_token = auth.credentials.token
        uid = auth.uid
        location = get_facebook_location(uid, access_token)[0]
        begin
          city = location["current_location"]["city"]
          region = location["current_location"]["state"]
          ciudad = City.where(:name => city).first
          if ciudad
            region = ciudad.region
          end
          if ciudad and region
            user.city_id = ciudad.id
            user.region_id = region.id
          end
        rescue
          #Aca deberiamos pedir completar el formulario
          print "Error"
        end
        user.facebook_password = true
        user.remote_foto_url = auth.info.image.sub("_normal", "").sub("http://","https://") + "?type=large"

        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end

  def self.http_get(domain,path,params)

    path = unless params.blank?
        path + "?" + params.collect { |k,v| "#{k}=#{CGI::escape(v.to_s)}" }.join('&')
      else
        path
    end

    uri = URI.parse(domain+path)
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE

    request = Net::HTTP::Get.new(uri.request_uri)

    response = http.request(request)
    response = response.body
    response = JSON.parse(response)
    return response
  end

  def self.get_facebook_location(uid, access_token)
      
      params = {
          :query => 'SELECT current_location FROM user WHERE uid='+uid ,
          :format => 'json',
          :access_token => access_token
      }
      http = http_get('https://api.facebook.com', '/method/fql.query', params)
      print http
      return http

  end


  def timestamp
    self.last_checked = DateTime.now
  end
end

web/app/controllers/user_controller.rb
class UserController < ApplicationController
	#Usuarios no identificados pueden ver el index y el perfil de otros users
	before_filter :authenticate_user!, :except => [:index, :perfil]
	  
	def index
		eventos_de_interes = []
		current_user.gustos.each do |gusto|
			eventos_de_interes += gusto.category.eventos.to_a
		end
		@interes = eventos_de_interes.each_slice(3).to_a
	end

	def perfil
		@user = User.find(params[:id])
		
		@userEventosAceptados = @user.reservas.aceptado
		@userCarpools = @user.publicacion_carpools
		#u.reservas.aceptado.first.user_evento.evento.name
		gustoUser = Gusto.where(user_id: @user.id)
		@gustos = []
		gustoUser.each do |gu|
			@gustos.push(Category.find(gu.category_id).name)
		end







	end

	def edit
    	@user = current_user
  	end

	def editar
		@user = User.find(params[:id])
	end



	
end

web/app/helpers/user_helper.rb
module UserHelper
end

web/app/views/user/index.html.erb
<div class="container">
	<% if @interes.count != 0 %>
	<!-- Eventos de tu interes -->
	<div class="row">
		<h2 class="page-header">Eventos de interés</h2>
		<!-- Creando las ventanitas de evento -->
		<div id="heroSlider2" class="carousel slide">
			<div class="carousel-inner">
				<% primer = true %>
				<% @interes.each do |eventos| %>
					<% if primer %>
						<div class="active item">
							<div id="eventosDeInteres" class="hero-unit carousel">
							<% eventos.each do |evento| %>
								<div class="col-lg-4 col-sm-6 text-center">
									<!-- Hipervinculo en la imagen, si no hay dejamos un placeholder-->
									<!-- Editar el placeholder para version final -->

									<%= link_to mostrar_evento_path(evento), 'data-no-turbolink' => true  do %>
									
										<% if evento.image.present? %>
											<% img = evento.image %>
										<% else %>
											<% img = 'http://placehold.it/200x200' %>
										<% end %> 

										<%= image_tag img , :class => "img-square img-responsive img-center" %>

									<% end %>

									<h3><%= evento.name %> </h3>
									<p> <%= evento.subtitle %> </p>
								</div>
							<%end%>
							</div>
						</div>
						<% primer = false %>
					<% else %>
						<div class="item">
							<div id="eventosDeInteres" class="hero-unit carousel">
							<!-- INICIO-->
								<% eventos.each do |evento| %>
									<div class="col-lg-4 col-sm-6 text-center">
									<!-- Hipervinculo en la imagen, si no hay dejamos un placeholder-->
									<!-- Editar el placeholder para version final -->
										<a href="<%= mostrar_evento_path(evento) %>">

										<img class="img-square img-responsive img-center" src="
										<% if evento.image.present? %>
											<%= evento.image %>
										<% else %>
											http://placehold.it/200x200
										<% end %> 
										" alt="">
										</a>
									<h3><%= evento.name %> </h3>
									<p> <%= evento.subtitle %> </p>
									</div>
								<% end %>
								<!-- FIN-->                  
								</div>
							</div>
						<% end %>
					<% end %>
					</div>
				<a class="left carousel-control" href="#heroSlider2" data-slide="prev">‹</a>
				<a class="right carousel-control" href="#heroSlider2" data-slide="next">›</a>
			</div>
	</div>
	<% end %>

	<div class="row">
		<h2 class="page-header">Preguntas Frecuentes</h2>
		<div class="panel-group" id="accordion">
		  <div class="panel panel-default">
		    <div class="panel-heading">
		      <h4 class="panel-title">
		        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
		          ¿Qué es un Carpool?
		        </a>
		      </h4>
		    </div>
		    <div id="collapseOne" class="panel-collapse collapse">
		      <div class="panel-body">
		        Carpool o Carpooling, es la práctica que consiste en compartir un automóvil con otras personas tanto para viajes periódicos como para trayectos puntuales. Si viajas en automóvil a un evento y tienes asientos libres, ésta es tu oportunidad, publica tu automóvil en Carryvent, compártelo y viaja acompañado.
		      </div>
		    </div>
		  </div>
		  <div class="panel panel-default">
		    <div class="panel-heading">
		      <h4 class="panel-title">
		        <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
		          ¿Cómo realizo una publicación Carpool?
		        </a>
		      </h4>
		    </div>
		    <div id="collapseTwo" class="panel-collapse collapse">
		      <div class="panel-body">
		        Ingresa al evento en el cual estas interesado, presiona "Publicar Carpool", rellena el formulario, selecciona el tipo de vehículo, confirma y ¡listo! Tendrás hecha tu publicación de Carpool al evento que quieres.
		      </div>
		    </div>
		  </div>
		  <div class="panel panel-default">
		    <div class="panel-heading">
		      <h4 class="panel-title">
		        <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
		          ¿Cómo me uno a un Carpool?
		        </a>
		      </h4>
		    </div>
		    <div id="collapseThree" class="panel-collapse collapse">
		      <div class="panel-body">
		        Ingresa al evento al cual quieres ir, revisa las "Ofertas Carpool" y entra en el detalle de la publicación, ahí podrás ver los datos del publicador, los datos de salida del vehículo, asientos disponibles, entre otros. Si estas conforme con la publicación, comunícate con el publicador para que puedan establecer un acuerdo monetario que beneficie a ambas partes, luego de esto, elige la cantidad de asientos que desees y presiona "Realizar petición". Solo te resta esperar la confirmación del publicador y estarás listo.
		      </div>
		    </div>
		  </div>
		</div>
	</div>


</div>	

web/app/views/user/perfil.html.erb
<% title "Perfil de " + @user.nombre %>
<!-- Page Content -->


<div class="container">
  <!-- Perfil -->
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <div class="panel-body">
          <div class="row">
            <div class="col-xs-12 col-sm-4 text-center">
              <img src="
                <% if @user.foto.present? %>
                  <%= @user.foto.url %>
                <% else %>
                  http://sintoniageek.com/wp-content/uploads/2011/03/avatar-facebook-defecto1.jpg
                <% end %>       
              " alt="" class="center-block img-responsive">
            </div><!--/col-->       
            <div class="col-xs-12 col-sm-8">
              <div> 
                
              </div>
              <h2><%= @user.nombre %></h2>
              <% if @user.city %>
                <p><b>Ciudad: </b> <%= @user.city.name + ", " + @user.region.name  %> </p>
              <% end %>
              <p><b>E-mail: </b> <%= @user.email %> </p>
              <% if @user.ranking %>
                <p><b>Ranking Carpool: </b>
                <div class="contenedorEstrellas">
                  <% for i in 0..(@user.ranking.round-1)%>
                    <span class="glyphicon glyphicon-star" id="estrellaColor"></span>
                  <% end %>
                  <% for i in 0..(4-@user.ranking.round)%>
                    <span class="glyphicon glyphicon-star" id="estrellaGris"></span>
                  <% end %>
                </div></p>
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal-<%= @user.id %>">Comentarios</button>
                        <div class="modal fade" id="myModal-<%= @user.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                          <div class="modal-dialog">
                            <div class="modal-content">
                              <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                                <h4 class="modal-title" id="myModalLabel">Comentarios</h4>
                              </div>
                              <div class="modal-body">
                                <%@user.rankings.each do |ranking|%>
                                  <b><%= ranking.comment %></b> <small><%= ranking.updated_at %></small>
                                  <hr>
                                <% end %>
                              </div>
                              <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                              </div>
                            </div>
                          </div>
                        </div>
              <% end %>
              <% if @user == current_user %>
                <a href="<%=edit_user_registration_path(@user)%>" class="btn btn-primary" style="float:right;">
                <i class="glyphicon glyphicon-edit"></i> 
                Editar Perfil </a>
              <% end %>
              <% if @gustos.length > 0 %>
                <p><strong>Gustos: </strong>
                  <% @gustos.each do |g| %>
                    <span class="label label-info tags"><%= g %></span> 
                  <% end %>
                </p>
              <% end %>
            </div><!--/col-->            
          </div><!--/row-->
        </div><!--/panel-body-->
      </div>
    </div>
    <!-- Eventos Asistidos -->
    <div class="row">
      <div class="col-md-12">
        <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">Eventos Asistidos</h4>
          </div>

          <% if @userEventosAceptados.count != 0 %>
          <div  class="asistidos-container" >
            <table class="table table-striped">
              <thead>
                <tr>
                  <td>Nombre</td>
                  <td>Fecha</td>
                  <td>Pasajes</td>
                </tr>
              </thead>
              <tbody>
                <% @userEventosAceptados.each do |ea| %>
                <tr>
                  <td><%= ea.user_evento.evento.name %></td>
                  <td><%= ea.user_evento.evento.date %></td>
                  <td>
                    <% if current_user.present? && current_user == ea.user_evento.user %>
                      <% ea.pasajes.each do |p| %>
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal-<%= p.id %>">n° <%= p.asiento %></button>
                        <div class="modal fade" id="myModal-<%= p.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                          <div class="modal-dialog">
                            <div class="modal-content">
                              <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                                <h4 class="modal-title" id="myModalLabel">QR Asiento n° <%= p.asiento %></h4>
                              </div>
                              <div class="modal-body">
                                <% qr = RQRCode::QRCode.new( p.codigo, :size => 4, :level => :h ) %>
                                <% @png = qr.to_img.resize(300,300).to_data_url %>
                                <center><%= image_tag @png %></center>
                              </div>
                              <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                              </div>
                            </div>
                          </div>
                        </div>
                      <% end %>
                    <% end %>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <% else %>
            <div class="panel-body">
              <p>¡No ha asistido a eventos hasta el momento!</p>
            </div>
          <% end %>
          
        </div>
      </div>
        <div class="col-md-6">
           <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">Carpools Publicados</h4>
            </div>
            <% if @userCarpools.count != 0 %>
              
              <table class="table table-striped">
              
                <thead>
                  <tr>
                    <th>Nombre</th>
                    <th>Fecha</th>
                    <th>Tipo Vehiculo</th>
                    <th> </th>
                  </tr>
                </thead>            
              <tbody>
                <% @userCarpools.each do |c| %>
                  <tr>
                    <td><%= c.evento.name %></td>
                    <td><%= c.fecha %></td>
                    <td><%= c.tipo_vehiculo %></td>
                    <% if current_user %>
                      <td><%= link_to "Ver los detalles", mostrar_carpool_path(c.evento.id, c.id) %></td>
                    <% else %>
                      <td>Ver los detalles</td>
                    <% end %>
                  </tr>
                <% end %>
              </tbody>
              </table>
              
            <% else %>
              <div class="panel-body">
                <p>No tiene publicaciones de carpool hasta el momento!</p>
              </div>
            <% end %>
            
          </div>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /.container -->


<!-- jQuery Version 1.11.0 -->
<script src="js/jquery-1.11.0.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="js/bootstrap.min.js"></script>